// examples/svelte/src/components/TodoList.svelte
<script lang="ts">
  import * as model from '../models/Todos.svelte';

  const {newTodoText, todos} = model;

  const addTodo = (e: KeyboardEvent) => {
    if (e.key === 'Enter') {
      const text = (e.currentTarget as HTMLInputElement).value;
      model.addTodo(text);
      newTodoText.value = '';
    }
  };

  const toggleTodo = (id: number) => {
    model.toggleTodo(id);
  };

  const changeNewTodo = (e: Event) => {
    model.changeNewTodoText((e.currentTarget as HTMLInputElement).value);
  };
</script>

<h4>Todos</h4>

<input
        type="text"
        placeholder="New todo"
        value={newTodoText.value}
        oninput={changeNewTodo}
        onkeydown={addTodo}
/>

<ol>
    {#each todos as todo(todo.id)}
        <li>
            <label style:text-decoration={todo.isCompleted ? 'line-through' : 'none' }>
                <input
                        type="checkbox"
                        checked={todo.isCompleted}
                        onchange={() => toggleTodo(todo.id)}
                />
                {todo.text}
            </label>
        </li>
    {/each}
</ol>

// examples/react-zustand/src/components/TodoList.tsx
import {type ChangeEventHandler, type KeyboardEventHandler, useRef} from 'react';
import {useTodosStore} from '../models/Todos';

export default function TodoList() {
  const todos = useTodosStore();
  const newTodoText = useRef<HTMLInputElement>(null);

  const addTodo: KeyboardEventHandler<HTMLInputElement> = (e) => {
    if (e.key === 'Enter') {
      todos.addTodo(e.currentTarget.value);

      if (newTodoText.current) {
        newTodoText.current.value = '';
      }
    }
  };

  const toggleTodo = (id: number) => {
    todos.toggleTodo(id);
  };

  const changeNewTodo: ChangeEventHandler<HTMLInputElement> = (e) => {
    todos.changeNewTodoText(e.currentTarget.value);
  };

  return (
    <>
      <h4>Todos</h4>

      <input
        type="text"
        placeholder="New todo"
        ref={newTodoText}
        onKeyDown={addTodo}
        onChange={changeNewTodo}
      />

      <ol>
        {todos.todos.map((todo) => (
          <li key={todo.id}>
            <label style={{textDecoration: todo.isCompleted ? 'line-through' : 'none'}}>
              <input
                type="checkbox"
                checked={todo.isCompleted || false}
                onChange={() => toggleTodo(todo.id)}
              />

              {todo.text}
            </label>
          </li>
        ))}
      </ol>
    </>
  );
}
