// examples/svelte/src/components/App.svelte
<script lang="ts">
  import {useSaga} from '@promise-saga/plugin-svelte';
  import {useDebounce} from '../saga';
  import {listenTodoToggles} from '../models/Todos.sagas';
  import {changeNewTodoText} from '../models/Todos.svelte';
  import TodoList from './TodoList.svelte';
  import SagaCheckbox from './SagaCheckbox.svelte';

  const listenTogglesFlow = useSaga(listenTodoToggles);
  const logNewTodoFlow = useDebounce(1000, changeNewTodoText, console.log);
</script>

<div>
    <label>
        <SagaCheckbox flow={logNewTodoFlow}/>
        Log new todo text, debounce 1000ms
    </label>
</div>

<div>
    <label>
        <SagaCheckbox flow={listenTogglesFlow}/>
        Log todos toggling, count by 3
    </label>
</div>

<TodoList/>

// examples/vue-pinia/src/components/App.vue
<script setup lang="ts">
import {FnAction} from '@promise-saga/core';
import {useSaga} from '@promise-saga/plugin-vue';
import {useDebounce} from '@/store/saga';
import {useTodosStore} from '@/models/Todos';
import {listenTodoToggles} from '@/models/Todos.sagas';
import SagaCheckbox from '@/components/SagaCheckbox.vue';
import TodoList from './TodoList.vue';

const todosStore = useTodosStore();

const listenTogglesFlow = useSaga(listenTodoToggles);
const logNewTodoFlow = useDebounce(1000, todosStore.changeNewTodoText as FnAction, console.log);
</script>

<template>
  <div>
    <label>
      <SagaCheckbox :flow="logNewTodoFlow" />
      Log new todo text, debounce 1000ms
    </label>
  </div>

  <div>
    <label>
      <SagaCheckbox :flow="listenTogglesFlow" />
      Log todos toggling, count by 3
    </label>
  </div>

  <TodoList />
</template>
