// examples/svelte/src/components/TodoList.svelte
<script lang="ts">
  import * as model from '../models/Todos.svelte';

  const {newTodoText, todos} = model;

  const addTodo = (e: KeyboardEvent) => {
    if (e.key === 'Enter') {
      const text = (e.currentTarget as HTMLInputElement).value;
      model.addTodo(text);
      newTodoText.value = '';
    }
  };

  const toggleTodo = (id: number) => {
    model.toggleTodo(id);
  };

  const changeNewTodo = (e: Event) => {
    model.changeNewTodoText((e.currentTarget as HTMLInputElement).value);
  };
</script>

<h4>Todos</h4>

<input
        type="text"
        placeholder="New todo"
        value={newTodoText.value}
        oninput={changeNewTodo}
        onkeydown={addTodo}
/>

<ol>
    {#each todos as todo(todo.id)}
        <li>
            <label style:text-decoration={todo.isCompleted ? 'line-through' : 'none' }>
                <input
                        type="checkbox"
                        checked={todo.isCompleted}
                        onchange={() => toggleTodo(todo.id)}
                />
                {todo.text}
            </label>
        </li>
    {/each}
</ol>

// examples/vue-pinia/src/components/TodoList.vue
<script setup lang="ts">
import {storeToRefs} from 'pinia';
import {useTodosStore} from '@/models/Todos';

const todosStore = useTodosStore();
const {todos, newTodoText} = storeToRefs(todosStore);

const addTodo = (e: KeyboardEvent) => {
  if (e.key === 'Enter') {
    const text = (e.currentTarget as HTMLInputElement).value;
    todosStore.addTodo(text);
    todosStore.changeNewTodoText('');
  }
};

const toggleTodo = (id: number) => {
  todosStore.toggleTodo(id);
};

const changeNewTodo = (e: Event) => {
  todosStore.changeNewTodoText((e.currentTarget as HTMLInputElement).value);
};
</script>

<template>
  <h4>Todos</h4>

  <input
    type="text"
    placeholder="New todo"
    :value="newTodoText"
    @input="changeNewTodo"
    @keydown="addTodo"
  />

  <ol>
    <li v-for="todo in todos" v-bind:key="todo.id">
      <label :style="{ textDecoration: todo.isCompleted ? 'line-through' : 'none' }">
        <input
          type="checkbox"
          :checked="todo.isCompleted || false"
          @change="toggleTodo(todo.id)"
        />

        {{ todo.text }}
      </label>
    </li>
  </ol>
</template>
